### ISSUE TITLE
L'appli ne lit pas encore les sous-répertoires (test)

### ISSUE THREAD

**Issue by MujusPrez** [Asso-MO5/instauto-shuffle-lite#3]
Hello ! 
L'appli ne lit pas encore des sous-répertoires qui permettront du coup de stocker un fichier texte (description.txt ou autre) dans lequel un texte général à autopublier relatif à ce répertoire sera utilisé par défaut. Il existe toujours la posssibilité également de définir un fichier texte du nom de l'image (.txt) qui peut contenir une description unitaire, et qui sera si trouvée prioritaire à la description générale du répertoire.

Bisou :)

**Comment by kazerlelutin** [comment]
Fixé dans la V.0.1.0
