### ISSUE TITLE
Problème de caractères accentués sous Windows 10

### ISSUE THREAD

**Issue by MujusPrez** [Asso-MO5/instauto-shuffle-lite#5]
Hello !
Après avoir ouvert l'appli de texte par défaut sous windows (notepad), le texte est bien sauvegardé mais les caractères accentués sont pétés.  Exemple : 
  "defaultText": "Collections Association MO5, prÃ©servation du patrimoine numÃ©rique.\r\nAdhÃ©rez, soutenez l'assocation et la sauvegarde de notre culture !\r\n\r\n#mo5.com #preservation #patrimoine #numerique"

**Comment by kazerlelutin** [comment]
Voir à récuper le Mine Type du fichier

**Comment by kazerlelutin** [comment]
Regarde la string et le type que Inquirer envoi

**Comment by kazerlelutin** [comment]
https://www.npmjs.com/package/chardet voir ici
